### PR TITLE
improvements in user-speech-interruption-detection logic and handling.

### PR DESCRIPTION
**Pull request by joslat**
Now the user-interruption logic works and also the buffer is cleaned so no leftover audio is left playing. 
fixes issue: https://github.com/fuwei007/OpenAI-realtimeapi-dotnetsdk/issues/1

### CODE REVIEW

**Comment by joslat** [comment]
Hi @fuwei007 / @FrankFuAM  Any Thoughts on the PR?

**Comment by fuwei007** [comment]
@joslat 
     I think this already fixed on the dev branch. I will double check it and review the PR see if we need apply your changes. Probably I need cherry pick some your changes.

Thanks

Frank

**Comment by JackLi-123** [comment]
Have pushed speech interruption detection bug fix to main branch as well as adding WinForm control, closing this PR.

**Comment by joslat** [comment]
Nice, thank you! :)

**Pull request closed without merging**
